# Generated by Django 4.2.4 on 2026-08-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceroom',
            name='description',
            field=models.TextField(blank=True, help_text='Describe the objectives or scope of the room.', null=True),
        ),
        migrations.AddField(
            model_name='workspaceroom',
            name='focus',
            field=models.CharField(blank=True, help_text='Primary technology stack or focus area (e.g., Python/Django)', max_length=100, null=True),
        ),
    ]
